// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIGi40ZeLzSIznfth4T7Lfo7vNUXu9b38',
    appId: '1:319025793022:web:481b62aaaf8d401032a2af',
    messagingSenderId: '319025793022',
    projectId: 'paralat2-71b62',
    authDomain: 'paralat2-71b62.firebaseapp.com',
    storageBucket: 'paralat2-71b62.appspot.com',
    measurementId: 'G-NNJ62MSCBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM9BZIVAmzYkkkpAzYTvpQEWaPwJ6w9Yw',
    appId: '1:319025793022:android:685146e366ef2b5f32a2af',
    messagingSenderId: '319025793022',
    projectId: 'paralat2-71b62',
    storageBucket: 'paralat2-71b62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7UrFHsoTn0PTqkOHWogxbsPYq6hBPT_k',
    appId: '1:319025793022:ios:edc09aea9b10114732a2af',
    messagingSenderId: '319025793022',
    projectId: 'paralat2-71b62',
    storageBucket: 'paralat2-71b62.appspot.com',
    iosBundleId: 'com.example.paralat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7UrFHsoTn0PTqkOHWogxbsPYq6hBPT_k',
    appId: '1:319025793022:ios:edc09aea9b10114732a2af',
    messagingSenderId: '319025793022',
    projectId: 'paralat2-71b62',
    storageBucket: 'paralat2-71b62.appspot.com',
    iosBundleId: 'com.example.paralat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIGi40ZeLzSIznfth4T7Lfo7vNUXu9b38',
    appId: '1:319025793022:web:91d5a86067c0e80f32a2af',
    messagingSenderId: '319025793022',
    projectId: 'paralat2-71b62',
    authDomain: 'paralat2-71b62.firebaseapp.com',
    storageBucket: 'paralat2-71b62.appspot.com',
    measurementId: 'G-G1W45STFMV',
  );
}
